### ISSUE TITLE
Remove phantomjs dependency

### ISSUE THREAD

**Issue by huston007** [vitalets/sinon-chrome#2]
Hello. First of all, thank you for a great util for testing chrome API related code.

But I don't use phantom in my tests. That's why I ask you to remove PhandomJS peer dependency from your package.json - I don't want to store it.

**Comment by vitalets** [comment]
removed.
thanks!

**Comment by huston007** [comment]
@vitalets great!

**Comment by huston007** [comment]
@vitalets Please publish update to NPM.

**Comment by vitalets** [comment]
Hmm, it's already done.
What is output of your `npm show sinon-chrome` ?
