### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BigBlueHat** [vitalets/sinon-chrome#8]
First, thanks so much for making this! I was in the process of mocking all the chrome.* bits that I needed, but it looks like you've already done that! Much thanks. :smile_cat: 

Second, I wondered if you could add a `LICENSE` file and/or `license` declaration in the `package.json` file. Without that--at least in the US--this library is essentially All Rights Reserved.

MIT, BSD, or Apache are pretty fabulous for this sort of project. `sinon` itself is BSD-3-clause. `karma-sinon-chrome` (which wraps this library) is MIT. It'd be super helpful to have one selected for this library also (see "none license" https://www.npmjs.com/package/sinon-chrome)

It looks like [you've used the MIT before](https://github.com/vitalets/checklist-model/blob/master/LICENSE.txt), so I'll assume (for now) that's where this is headed. :wink: But a license statement would help for sure. :smile:

Thanks! :tophat:

**Comment by acvetkov** [comment]
Hi, @BigBlueHat . 
Thanks for your issue. I've updated license field in package.json
https://github.com/vitalets/sinon-chrome/blob/master/package.json#L39
